version: '3.8'
services:
  authserver:
    build:
      context: ./authserver
      target: development
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=postgresserver:5432/gizmodb
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - ISSUER=http://authserver:8080
    depends_on:
      - postgresserver

  resourceserver:
    build:
      context: ./resourceserver
      target: development
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_URL=postgresserver:5432/gizmodb
      - POSTGRES_USERNAME=user
      - POSTGRES_PASSWORD=password
      - ISSUER_URI=http://authserver:8080
    depends_on:
      - postgresserver
      - authserver

  react-client:
    build:
      context: ./react-client
      target: development
    ports:
      - "3000:3000"

  postgresserver:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gizmodb
    volumes:
      - pg_data:/var/lib/postgresql/data
      - pg_config:/etc/postgresql
volumes:
  pg_data:
  pg_config: