version: '3.8'
services:
  authserver:
    image: hamzul/authserver:latest
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ISSUER=http://authserver:8080
      - CLIENT_URI=${CLIENT_URI}

  resourceserver:
    image: hamzul/resourceserver:latest
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ISSUER_URI=http://authserver:8080
      - CLIENT_URI=${CLIENT_URI}
    depends_on:
      - authserver