version: '3.8'
services:
  authserver:
    image: hamzul/authserver:latest
    ports:
      - "80:8080"
    environment:
      - SERVER_PORT=8080
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ISSUER=${ISSUER}
      - CLIENT_URI=${CLIENT_URI}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PW=${ADMIN_PW}

  resourceserver:
    image: hamzul/resourceserver:latest
    ports:
      - "81:8081"
    environment:
      - SERVER_PORT=8081
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ISSUER_URI=${ISSUER_URI}
      - CLIENT_URI=${CLIENT_URI}
      - ACTIVE_PROFILE=${ACTIVE_PROFILE}
    depends_on:
      - authserver