spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080

server:
  port: 8081