spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/gizmo-db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:8080}


management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,threaddump

server:
  tomcat:
    mbeanregistry:
      enabled: true
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
