logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gizmodb
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
