logging:
  level:
    org.springframework.security: trace

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432/gizmo-db}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
