name: build
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        image_name: ["authserver", "resourceserver"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@3
        with:
          java-version: 17
          distribution: "corretto"

      #
      - name: Build
        working-directory: ${{ matrix.image_name }}
        run:
          ./gradlew bootJar
          mv build/libs/$(ls build/libs) app.jar
      #

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GIZMO_DHUB_TOKEN }}

      - name: Extract image metadata for ${{ matrix.image_name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_OWNER 3}/${{ matrix.image_name }}

      - name: build and push ${{ matrix.image_name }}
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.image_name }}
          file: ${{ matrix.image_name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels : ${{ steps.meta.outputs.labels }}
          secrets: |
            DOCKERHUB_TOKEN=${{ secrets.GIZMO_DHUB_TOKEN }}
